import type { Roadmap } from '../_types';

export const MOCK_ROADMAPS: Roadmap[] = [
  {
    id: '1',
    title: 'React 마스터 로드맵',
    description: 'React의 기초부터 고급 개념까지',
    icon: 'deployed_code',
    iconColor: '#dc2626',
    iconBgColor: '#fee2e2',
    progress: 50,
    metadata: {
      type: 'personal',
      stepsCount: 10,
      status: 'in-progress',
    },
    createdAt: '2024-01-15',
    updatedAt: '2024-01-20',
  },
  {
    id: '2',
    title: 'JavaScript 완벽 가이드',
    description: 'JavaScript 핵심 개념 정복',
    icon: 'language',
    iconColor: '#e6c200',
    iconBgColor: '#f9ffa6',
    progress: 75,
    metadata: {
      type: 'personal',
      stepsCount: 12,
      status: 'in-progress',
    },
    createdAt: '2024-01-10',
    updatedAt: '2024-01-22',
  },
  {
    id: '3',
    title: 'TypeScript 심화',
    description: 'TypeScript 고급 타입 시스템',
    icon: 'code',
    iconColor: '#16a34a',
    iconBgColor: '#dcfce7',
    progress: 30,
    metadata: {
      type: 'team',
      stepsCount: 8,
      status: 'in-progress',
    },
    createdAt: '2024-01-12',
    updatedAt: '2024-01-18',
  },
  {
    id: '4',
    title: 'Next.js 프로젝트',
    description: 'Next.js로 풀스택 앱 만들기',
    icon: 'web',
    iconColor: '#2666dc',
    iconBgColor: '#dbeafe',
    progress: 100,
    metadata: {
      type: 'personal',
      stepsCount: 15,
      status: 'completed',
    },
    createdAt: '2024-01-05',
    updatedAt: '2024-01-19',
  },
  {
    id: '5',
    title: 'CSS 마스터',
    description: 'CSS Grid와 Flexbox 완전 정복',
    icon: 'palette',
    iconColor: '#a826dc',
    iconBgColor: '#f3e8ff',
    progress: 60,
    metadata: {
      type: 'personal',
      stepsCount: 10,
      status: 'in-progress',
    },
    createdAt: '2024-01-08',
    updatedAt: '2024-01-21',
  },
  {
    id: '6',
    title: '알고리즘 정복',
    description: '코딩 테스트 대비 알고리즘',
    icon: 'psychology',
    iconColor: '#ea580c',
    iconBgColor: '#ffedd5',
    progress: 40,
    metadata: {
      type: 'team',
      stepsCount: 20,
      status: 'in-progress',
    },
    createdAt: '2024-01-03',
    updatedAt: '2024-01-17',
  },
  {
    id: '7',
    title: 'Git & GitHub',
    description: '버전 관리 완벽 가이드',
    icon: 'source',
    iconColor: '#dc2626',
    iconBgColor: '#fee2e2',
    progress: 100,
    metadata: {
      type: 'personal',
      stepsCount: 7,
      status: 'completed',
    },
    createdAt: '2024-01-01',
    updatedAt: '2024-01-15',
  },
  {
    id: '8',
    title: 'Node.js Backend',
    description: 'Node.js로 REST API 구축',
    icon: 'storage',
    iconColor: '#16a34a',
    iconBgColor: '#dcfce7',
    progress: 20,
    metadata: {
      type: 'team',
      stepsCount: 14,
      status: 'in-progress',
    },
    createdAt: '2024-01-14',
    updatedAt: '2024-01-20',
  },
  {
    id: '9',
    title: 'Database 설계',
    description: 'SQL과 NoSQL 데이터베이스',
    icon: 'database',
    iconColor: '#2666dc',
    iconBgColor: '#dbeafe',
    progress: 85,
    metadata: {
      type: 'personal',
      stepsCount: 11,
      status: 'in-progress',
    },
    createdAt: '2024-01-07',
    updatedAt: '2024-01-22',
  },
  {
    id: '10',
    title: 'DevOps 입문',
    description: 'CI/CD 파이프라인 구축',
    icon: 'settings',
    iconColor: '#a826dc',
    iconBgColor: '#f3e8ff',
    progress: 0,
    metadata: {
      type: 'team',
      stepsCount: 9,
      status: 'not-started',
    },
    createdAt: '2024-01-16',
    updatedAt: '2024-01-16',
  },
  {
    id: '11',
    title: 'AWS 클라우드',
    description: 'AWS 서비스 활용법',
    icon: 'cloud',
    iconColor: '#ea580c',
    iconBgColor: '#ffedd5',
    progress: 55,
    metadata: {
      type: 'personal',
      stepsCount: 13,
      status: 'in-progress',
    },
    createdAt: '2024-01-09',
    updatedAt: '2024-01-21',
  },
  {
    id: '12',
    title: 'Docker & Kubernetes',
    description: '컨테이너 오케스트레이션',
    icon: 'widgets',
    iconColor: '#e6c200',
    iconBgColor: '#f9ffa6',
    progress: 100,
    metadata: {
      type: 'team',
      stepsCount: 16,
      status: 'completed',
    },
    createdAt: '2024-01-02',
    updatedAt: '2024-01-18',
  },
  {
    id: '13',
    title: 'GraphQL API',
    description: 'GraphQL로 유연한 API 구축',
    icon: 'api',
    iconColor: '#dc2626',
    iconBgColor: '#fee2e2',
    progress: 45,
    metadata: {
      type: 'personal',
      stepsCount: 10,
      status: 'in-progress',
    },
    createdAt: '2024-01-11',
    updatedAt: '2024-01-20',
  },
  {
    id: '14',
    title: 'Testing 완벽 가이드',
    description: '단위 테스트부터 E2E까지',
    icon: 'bug_report',
    iconColor: '#16a34a',
    iconBgColor: '#dcfce7',
    progress: 70,
    metadata: {
      type: 'team',
      stepsCount: 12,
      status: 'in-progress',
    },
    createdAt: '2024-01-06',
    updatedAt: '2024-01-19',
  },
  {
    id: '15',
    title: 'Web Security',
    description: '웹 보안 기초와 실전',
    icon: 'security',
    iconColor: '#2666dc',
    iconBgColor: '#dbeafe',
    progress: 35,
    metadata: {
      type: 'personal',
      stepsCount: 8,
      status: 'in-progress',
    },
    createdAt: '2024-01-13',
    updatedAt: '2024-01-21',
  },
];
