import type { RoadmapItem } from '@/lib/types/dashboard';

export const MOCK_ROADMAPS: RoadmapItem[] = [
  {
    id: '1',
    title: 'React 마스터 로드맵',
    icon: 'deployed_code',
    color: 'red',
    category: 'personal',
    steps: 10,
    status: 'in-progress',
    progress: 50,
  },
  {
    id: '2',
    title: 'TypeScript 완벽 가이드',
    icon: 'code',
    color: 'blue',
    category: 'personal',
    steps: 8,
    status: 'in-progress',
    progress: 75,
  },
  {
    id: '3',
    title: 'Next.js 실전 프로젝트',
    icon: 'javascript',
    color: 'yellow',
    category: 'team',
    steps: 12,
    status: 'in-progress',
    progress: 30,
  },
  {
    id: '4',
    title: 'Node.js 백엔드 개발',
    icon: 'database',
    color: 'green',
    category: 'personal',
    steps: 15,
    status: 'in-progress',
    progress: 60,
  },
  {
    id: '5',
    title: 'GraphQL API 설계',
    icon: 'network_intelligence',
    color: 'purple',
    category: 'team',
    steps: 7,
    status: 'completed',
    progress: 100,
  },
];
